// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRi0k1GQvZcVHQAsAsLQaZrQ6Yzx4FfMg',
    appId: '1:1049818433687:web:d661cb2a9fe4cf66fcc1d2',
    messagingSenderId: '1049818433687',
    projectId: 'yalnizde-2cf88',
    authDomain: 'yalnizde-2cf88.firebaseapp.com',
    storageBucket: 'yalnizde-2cf88.firebasestorage.app',
    measurementId: 'G-JV1NCKS4M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoHS8xGQ_WEyAT95XMPbh-aumLEEcVPkY',
    appId: '1:1049818433687:android:adfee1ef7d1aaa05fcc1d2',
    messagingSenderId: '1049818433687',
    projectId: 'yalnizde-2cf88',
    storageBucket: 'yalnizde-2cf88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJLS3TBuQUrsyB39uUdB7n1efykbmFR1I',
    appId: '1:1049818433687:ios:b55ad95b4d509f85fcc1d2',
    messagingSenderId: '1049818433687',
    projectId: 'yalnizde-2cf88',
    storageBucket: 'yalnizde-2cf88.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJLS3TBuQUrsyB39uUdB7n1efykbmFR1I',
    appId: '1:1049818433687:ios:b55ad95b4d509f85fcc1d2',
    messagingSenderId: '1049818433687',
    projectId: 'yalnizde-2cf88',
    storageBucket: 'yalnizde-2cf88.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRi0k1GQvZcVHQAsAsLQaZrQ6Yzx4FfMg',
    appId: '1:1049818433687:web:22e874abfd6d60d3fcc1d2',
    messagingSenderId: '1049818433687',
    projectId: 'yalnizde-2cf88',
    authDomain: 'yalnizde-2cf88.firebaseapp.com',
    storageBucket: 'yalnizde-2cf88.firebasestorage.app',
    measurementId: 'G-FN50GB5H5H',
  );
}
